apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newName: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newTag: c005ab0a30cc1978db2d8a18d65497e659585b2d
resources:
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
