apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newName: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newTag: 51d8be4938d4e3b72d7fcd1e39c9b46063d55629
resources:
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
