apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newName: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newTag: cd3d68cc0ae72cf1525e2c9065081d9f5fb17ee2
resources:
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
