apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newName: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-market-backend
  newTag: 24af34a6aa91eaed765350597d5cbd577ef34d8d
resources:
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
