apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-backend
  newName: 619376925781.dkr.ecr.ap-northeast-2.amazonaws.com/cx-auction-backend
  newTag: local
resources:
- secret.yaml
- deployment.yaml
- service.yaml
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml
- decreateReplicas.yaml
