apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
  namespace: default
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
      nodePort: 31000

  selector:
    app: nestjs-app
  type: NodePort